export { default as CHROME_GREEN } from './images/chrome-green.svg';
export { default as CHROME } from './images/chrome.svg';
export { default as ENHANCHMENT } from './images/ENHANCHMENT.png';
export { default as EXPORT } from './images/EXPORT.png';
export { default as FACEBOOK } from './images/facebook.svg';
export { default as BACKGROUND } from './images/footer image.svg';
export { default as MENU } from './images/hamburger.svg';
export { default as HERO_BG } from './images/image 1.png';
export { default as INSTAGRAM } from './images/instagram.svg';
export { default as LOGO } from './images/logo.svg';
export { default as API_KEY } from './images/Pasted image.png';
export { default as PAYMENT } from './images/Payment process.png';
export { default as RATING } from './images/rating.png';
export { default as REPORT } from './images/REPORT.png';
export { default as API_NAME } from './images/Screenshot From 2024-11-10 18-53-12.png';
export { default as CUSTOMER } from './images/service.png';
export { default as SCREEN_SHOT } from './images/SS.png';
export { default as TRANSACTION } from './images/transaction.png';
export { default as TWITTER } from './images/twitter.svg';
export { default as API_PAGE } from './images/Untitled design.png';
export { default as WEBHOOK_CREATE } from './images/webhook_create.png';
export { default as WEBHOOK_INPUT } from './images/webhook_input.png';
export { default as WEBHOOK_VALIDATE } from './images/webhook_validate.png';
export { default as WHATSAPP } from './images/whatsapp.svg';
